# Generated by Django 3.0.7 on 2020-07-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200710_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sample',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
